const asyncHandler = require('../utils/asyncHandler');
const sendEmail = require('../utils/sendEmail');

// Helper to escape HTML characters for safety in email clients
const escapeHTML = (str) => {
  if (typeof str !== 'string') return str;
  return str.replace(/[&<>'"]/g, 
    (tag) => ({
      '&': '&amp;',
      '<': '&lt;',
      '>': '&gt;',
      "'": '&#39;',
      '"': '&quot;'
    }[tag] || tag)
  );
};

// @desc    Submit contact form and dispatch email notification
// @route   POST /api/contact
// @access  Public
exports.submitContactForm = asyncHandler(async (req, res) => {
  const { name, email, message } = req.body;

  // Sanitize fields to protect against HTML injection in email client
  const sanitizedName = escapeHTML(name);
  const sanitizedEmail = escapeHTML(email);
  const sanitizedMessage = escapeHTML(message);
  
  const submittedAt = new Date();
  
  // Format the email using a clean layout
  const htmlContent = `
    <div style="font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; max-width: 600px; margin: 20px auto; padding: 25px; border: 1px solid #e2e8f0; border-radius: 12px; background-color: #ffffff; color: #1e293b; box-shadow: 0 4px 12px rgba(0, 0, 0, 0.03);">
      <div style="text-align: center; border-bottom: 2px solid #f1f5f9; padding-bottom: 15px; margin-bottom: 20px;">
        <h2 style="color: #6366f1; margin: 0; font-size: 24px; font-weight: 700;">P2PLearn</h2>
        <p style="color: #64748b; margin: 5px 0 0 0; font-size: 14px;">New Contact Form Inquiry</p>
      </div>
      
      <table style="width: 100%; border-collapse: collapse; margin-bottom: 25px;">
        <tr>
          <td style="padding: 10px 0; font-weight: 600; color: #64748b; width: 130px; border-bottom: 1px solid #f1f5f9; font-size: 14px;">Name:</td>
          <td style="padding: 10px 0; color: #0f172a; border-bottom: 1px solid #f1f5f9; font-size: 14px; font-weight: 500;">${sanitizedName}</td>
        </tr>
        <tr>
          <td style="padding: 10px 0; font-weight: 600; color: #64748b; width: 130px; border-bottom: 1px solid #f1f5f9; font-size: 14px;">User Email:</td>
          <td style="padding: 10px 0; color: #0f172a; border-bottom: 1px solid #f1f5f9; font-size: 14px; font-weight: 500;">
            <a href="mailto:${sanitizedEmail}" style="color: #6366f1; text-decoration: none;">${sanitizedEmail}</a>
          </td>
        </tr>
        <tr>
          <td style="padding: 10px 0; font-weight: 600; color: #64748b; width: 130px; border-bottom: 1px solid #f1f5f9; font-size: 14px;">Submitted At:</td>
          <td style="padding: 10px 0; color: #0f172a; border-bottom: 1px solid #f1f5f9; font-size: 14px;">${submittedAt.toLocaleString()}</td>
        </tr>
      </table>
      
      <div style="background-color: #f8fafc; border-radius: 8px; padding: 20px; border: 1px solid #e2e8f0;">
        <h4 style="margin: 0 0 10px 0; color: #0f172a; font-size: 15px; font-weight: 600; border-bottom: 1px solid #e2e8f0; padding-bottom: 8px;">Message Content:</h4>
        <p style="margin: 0; line-height: 1.6; color: #334155; font-size: 14px; white-space: pre-wrap;">${sanitizedMessage}</p>
      </div>
      
      <div style="text-align: center; margin-top: 30px; font-size: 12px; color: #94a3b8; border-top: 1px solid #f1f5f9; padding-top: 15px;">
        This email was automatically generated by the P2PLearn Contact submission workflow.
      </div>
    </div>
  `;

  const textContent = `Name: ${name}\nUser Email: ${email}\nMessage:\n${message}\n\nSubmitted At: ${submittedAt.toLocaleString()}`;

  // Deliver the email directly to the developer
  await sendEmail({
    email: 'omtechservices.dev@gmail.com',
    subject: 'New Contact Form Submission - P2PLearn',
    message: textContent,
    html: htmlContent
  });

  res.status(200).json({
    success: true,
    message: 'Thank you for reaching out! Your message has been sent.'
  });
});
